In [2]:
import pandas as pd
df = pd.read_csv('board_df.csv')
df

Empty DataFrame
Columns: [game, date, matsto, malsto, rafsto, micdus, monkmi, joasto, darsar, janwie]
Index: []

In [11]:
dict = {'matsto':72,'rafsto':33}
dict['malsto'] = 33
dict = pd.DataFrame(dict,index=[0])

test = pd.concat([df,dict])
test

  game date matsto malsto rafsto micdus monkmi joasto darsar janwie
0  NaN  NaN     72     33     33    NaN    NaN    NaN    NaN    NaN